In [6]:
! pip install opencv-python==4.2.0.32

  Using cached opencv_python-4.2.0.32-cp38-cp38-manylinux1_x86_64.whl (28.2 MB)


In [9]:
! pip install matplotlib==3.3.3

  Using cached matplotlib-3.3.3-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
  Using cached kiwisolver-1.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
  Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
  Using cached Pillow-10.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)


In [10]:
import tensorflow as tf
import sys  
import os
sys.path.append(os.path.realpath('../../src'))
import cv2
import os
import glob
import numpy as np
import matplotlib.pyplot as plt

In [12]:
model = tf.keras.models.load_model('../../models/saved_model/saral_hwd_model_itr3.h5')

2023-08-16 16:52:58.856574: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-08-16 16:52:58.856608: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ti-lap-492): /proc/driver/nvidia/version does not exist
2023-08-16 16:52:58.856877: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [18]:
path = '/home/venkateshiyer/Desktop/fulljson_Aug923/images/*'
for img1 in sorted(glob.iglob(path)):
        img=cv2.imread(img1)
        print(img)
        img_name = img1.split('/')[-1]
        img=cv2.resize(img,(28,28))
        write_img = img
        img= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img = img.astype('float32') / 255.
        img= np.reshape(img,(1,28,28,1))
        res=model.predict(img)
        pred=res[0].argmax(axis=0)
        if pred==0:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/0/'+img_name+'.png',write_img)
        elif pred==1:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/1/'+img_name+'.png',write_img)
        elif pred==2:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/2/'+img_name+'.png',write_img)
        elif pred==3:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/3/'+img_name+'.png',write_img)
        elif pred==4:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/4/'+img_name+'.png',write_img)
        elif pred==5:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/5/'+img_name+'.png',write_img)
        elif pred==6:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/6/'+img_name+'.png',write_img)
        elif pred==7:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/7/'+img_name+'.png',write_img)
        elif pred==8:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/8/'+img_name+'.png',write_img)
        elif pred==9:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/9/'+img_name+'.png',write_img)
        elif pred==10:
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/10/'+img_name+'.png',write_img)
print('Done!')

[[[194 184 190]
  [187 180 185]
  [186 179 182]
  ...
  [186 179 182]
  [185 178 181]
  [184 177 180]]

 [[193 182 190]
  [189 182 187]
  [191 184 187]
  ...
  [188 181 184]
  [186 179 182]
  [188 181 184]]

 [[188 175 183]
  [186 176 182]
  [187 180 183]
  ...
  [188 181 184]
  [189 182 187]
  [187 180 185]]

 ...

 [[191 179 185]
  [165 155 161]
  [182 172 178]
  ...
  [187 180 183]
  [187 180 183]
  [188 181 184]]

 [[191 179 185]
  [168 158 164]
  [181 171 177]
  ...
  [187 180 183]
  [188 181 184]
  [189 182 185]]

 [[193 183 189]
  [174 164 170]
  [183 172 180]
  ...
  [187 180 183]
  [188 181 184]
  [191 184 187]]]
[[[244 228 215]
  [240 227 213]
  [240 227 211]
  ...
  [246 229 216]
  [244 228 215]
  [240 227 213]]

 [[216 200 187]
  [214 198 185]
  [216 200 187]
  ...
  [225 209 196]
  [224 208 195]
  [224 208 195]]

 [[204 187 174]
  [212 195 182]
  [213 196 183]
  ...
  [196 183 169]
  [196 180 167]
  [194 178 165]]

 ...

 [[232 219 205]
  [242 229 215]
  [237 224 210]
  ..

In [19]:
def pred_using_h5_digit(model, path, gt = None, prediction= None, wrong_results = None):
    result = {}
    wrong_results = {}
    gt=[]
    prediction = []
    wrong_count=0
    for img1 in sorted(glob.iglob(path)):
        img=cv2.imread(img1)
        img_name = img1.split('/')[-1]
        img=cv2.resize(img,(28,28))
        write_img = img
        img= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img = img.astype('float32') / 255.
        img= np.reshape(img,(1,28,28,1))
        res=model.predict(img)
        pred=res[0].argmax(axis=0)
        ground_truth = int(img1.split('/')[-2])
        gt.append(int(ground_truth))
        prediction.append(pred)
        result[img1] = pred
        if pred!= int(ground_truth):
            wrong_count+=1
            wrong_results[img1] = pred
            cv2.imwrite('/home/venkateshiyer/Desktop/fulljson_Aug923/wrong_preds/'+str(ground_truth)+'/'+img_name, write_img)
    accuracy = (len(glob.glob(path))-wrong_count)/len(glob.glob(path))
    return result, accuracy, gt, prediction, wrong_results

In [20]:
path = '/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/0/*'
result, accuracy, gt, prediction, wrong_results = pred_using_h5_digit(model,path)

In [25]:
! pip install scikit-learn


  Using cached scikit_learn-1.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)


In [26]:
print(accuracy)
from sklearn import metrics
print(metrics.classification_report(gt, prediction))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       124

    accuracy                           1.00       124
   macro avg       1.00      1.00      1.00       124
weighted avg       1.00      1.00      1.00       124



In [27]:
path = '/home/venkateshiyer/Desktop/fulljson_Aug923/class_wise/1/*'
result, accuracy, gt, prediction, wrong_results = pred_using_h5_digit(model,path)

In [28]:
print(accuracy)
from sklearn import metrics
print(metrics.classification_report(gt, prediction))

1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        73

    accuracy                           1.00        73
   macro avg       1.00      1.00      1.00        73
weighted avg       1.00      1.00      1.00        73

